# Shared constants for scraper modules

# SoM — full professors
full_professors_SoM = [
    "Adrian Rinscheid",
    "Alexander Braun",
    "Alexander Geissler",
    "Alexander Zimmermann",
    "Anastasia Kartasheva",
    "Andrea Back",
    "Andrea Barbon",
    "Andreas Grünbichler",
    "Andreas Hein",
    "Andreas Herrmann",
    "Andrei Ciortea",
    "Ann-Kristin Zobel",
    "Anna Elsner",
    "Anna Jasinenko",
    "Anna-Lena Horlemann",
    "Antoinette Weibel",
    "Arnold Rusch",
    "Barbara Weber",
    "Beatrix Eugster",
    "Benjamin Schindler",
    "Bernadette Dilger",
    "Bernhard Bermeitinger",
    "Björn Ambos",
    "Blagoy Blagoev",
    "Bruno Caprettini",
    "Bruno Mascello",
    "Bruno Rodrigues",
    "Can Gao",
    "Carl David Mildenberger",
    "Caspar Hirschi",
    "Charlotta Siren",
    "Chieh Hsu",
    "Chris Steyaert",
    "Christian Biener",
    "Christian Hildebrand",
    "Christian Laesser",
    "Christina Niklaus",
    "Christine Abbt",
    "Christoph Errass",
    "Christoph Lechner",
    "Christoph Müller",
    "Christophe Valmaggia",
    "Claudia Brühwiler",
    "Clemens Stachl",
    "Damian Borth",
    "Dania Achermann",
    "Daniel Cuonz",
    "Daniel Markus Häusermann",
    "Daria Berg",
    "Dennis Fehrenbacher",
    "Despoina Makariou",
    "Dietmar Grichnik",
    "Dirk Lehmkuhl",
    "Dirk Schäfer",
    "Dirk Zupancic",
    "Dominik Sachs",
    "Désirée Klingler",
    "Elgar Fleisch",
    "Elsa Massoc",
    "Emanuel de Bellis",
    "Emilia Garcia-Appendini",
    "Enrico De Giorgi",
    "Eri Bertsou",
    "Evangelos Souitaris",
    "Falk Uebernickel",
    "Federico Luisetti",
    "Felix Keller",
    "Felix Wortmann",
    "Florian Eugster",
    "Florian Schui",
    "Florian Wettstein",
    "Francesco Audrino",
    "Franco Lorandi",
    "Georg Guttmann",
    "Giedre Lideikyte Huber",
    "Gudrun Sander",
    "Guido Cozzi",
    "Guido Salvaneschi",
    "Hagen Völzer",
    "Hannah Smidt",
    "Harald Tuckermann",
    "Hardy Landolt",
    "Hato Schmeiser",
    "Heike Bruch",
    "Heiko Bergmann",
    "Ingrid Bauer-Hänsel",
    "Insa Lee Koch",
    "Isabella Hatak",
    "Isabelle Wildhaber",
    "Ivo Blohm",
    "J. Peter Murmann",
    "James Davis",
    "Jamie Gloor",
    "Jan Marco Leimeister",
    "Jana Mareckova",
    "Jelena Tosic",
    "Johanna Gollnhofer",
    "Johanna Kutz",
    "Johannes Binswanger",
    "Johannes Rüegg-Stürm",
    "Johannes Schöning",
    "Judith Ströhle",
    "Judith Walls",
    "Julia Franziska Hänni",
    "Julia Nentwich",
    "Julian Kölbel",
    "Jörg Metelmann",
    "Jürg Simon",
    "Karl Frauendorfer",
    "Karl Vincent",
    "Karolin Frankenberger",
    "Katarina Stanoevska",
    "Katerina Mitrokotsa",
    "Kathleen Kürschner Rauck",
    "Klaus Dingwerth",
    "Klaus Möller",
    "Konrad Adler",
    "Kuno Schedler",
    "Lorenz Engi",
    "Lucien Müller",
    "Lukas Glanzmann",
    "Lukas Gonon",
    "Lukas Gschwend",
    "Lyudmila Grigoryeva",
    "Manuel Rach",
    "Marc Arnold",
    "Marco Stacher",
    "Marcus Schögel",
    "Mariana Lopes da Fonseca",
    "Mariana Valente",
    "Markus Huggenberger",
    "Markus Kondziella",
    "Markus Müller-Chen",
    "Markus Schmid",
    "Martin Brown",
    "Martin Eggel",
    "Martin Eling",
    "Martin Eppler",
    "Martin Kolmar",
    "Martin Nerlinger",
    "Martin Wolf",
    "Martina Montauti",
    "Matias Dewey",
    "Matthias Fengler",
    "Matthias Mitterlechner",
    "Matthias Tietz",
    "Matthias Weber",
    "Maximilian Palmié",
    "Maël Schnegg",
    "Michael Festl",
    "Michael Lechner",
    "Michele Ittens",
    "Michèle Müller-Itten",
    "Michèle Sutter",
    "Miriam Buiten",
    "Miriam Meckel",
    "Monika Kurath",
    "Monika Simmler",
    "Moritz Loock",
    "Nadja Erk",
    "Naomi Haefner",
    "Nils Fürstenberg",
    "Nils Jent",
    "Nina Reiser",
    "Nora Markwalder",
    "Oliver Gassmann",
    "Paolo Piacquadio",
    "Patricia Egli",
    "Patrick Emmenegger",
    "Patrick Guidon",
    "Patrik Aspers",
    "Paul Söderlind",
    "Paula Bialski",
    "Peter Hettich",
    "Peter Hongler",
    "Peter Leibfried",
    "Peter Rohner",
    "Petrit Ademi",
    "Philipp Ebel",
    "Pietro Beritelli",
    "Rainer Krähenmann",
    "Ralf Imstepf",
    "Raoul Stocker",
    "Raphaela Cueni",
    "Reinhard Jung",
    "Reto Föllmi",
    "Rita Kesselring",
    "Robert Winter",
    "Roger Moser",
    "Roland Füss",
    "Roland Hodler",
    "Rolf Wüstenhagen",
    "Roman Capaul",
    "Ronny Seiger",
    "Sabine Seufert",
    "Sabrina Eisenbarth",
    "Samuel Häfner",
    "Sebastian Kernbach",
    "Seraina Grünewald",
    "Siegfried Handschuh",
    "Silvia Stroe",
    "Simon Grand",
    "Simon Mayer",
    "Stefan Bühler",
    "Stefan Morkötter",
    "Stefan Schmid",
    "Stefan Weik",
    "Stefano Ramelli",
    "Stephan Aier",
    "Stephan Böhm",
    "Susanne Fischer",
    "Suzanne Enzerink",
    "Sven Reinecke",
    "Tabea Lorenz",
    "Tami Dinh",
    "Tereza Tykvová",
    "Thierry Volery",
    "Thomas Berndt",
    "Thomas Beschorner",
    "Thomas Burri",
    "Thomas Friedli",
    "Thomas Grisaffi",
    "Thomas Grisold",
    "Thomas Rudolph",
    "Thomas Werlen",
    "Thomas Zellweger",
    "Tim Meyer",
    "Tina Freyburg",
    "Tobias Ebert",
    "Tomi Laamanen",
    "Ulrich Matter",
    "Ulrich Schmid",
    "Ulrike Baumöl",
    "Ulrike Landfester",
    "Urs Bertschinger",
    "Urs Fueglistaller",
    "Valentin Jentsch",
    "Vanessa Boanada Fuchs",
    "Veronica Barassi",
    "Vesa Pursiainen",
    "Vitaly Orlov",
    "Vito Roberto",
    "Winfried Koeniger",
    "Winfried Ruigrok",
    "Wolfgang Jenewein",
    "Zoe Jonassen",
]

# ---------------------------------------------------------------------------
# HSG programmes — used to validate student input and filter eligible supervisors
# ---------------------------------------------------------------------------

HSG_BACHELOR_PROGRAMMES = [
    "Bachelor of Arts HSG in Business Administration (B.A. HSG)",
    "Bachelor of Arts HSG in Economics (B.A. HSG)",
    "Bachelor of Arts HSG in International Affairs (B.A. HSG)",
    "Bachelor of Arts HSG in Business Innovation (B.A. HSG)",
    "Bachelor of Science HSG in Nursing Science (B.Sc. HSG)",
]

HSG_MASTER_PROGRAMMES = [
    "Master in Accounting and Finance (MAccFin)",
    "Master in Banking and Finance (MBF)",
    "Master in Business Innovation (MBI)",
    "Master in Economics (MEcon)",
    "Master in Finance (MF)",
    "Master in General Management (MGM)",
    "Master in Health Economics (MHEc)",
    "Master in International Affairs and Governance (MIA)",
    "Master in Law and Economics (MLE)",
    "Master in Management (MM)",
    "Master in Marketing Management (MMM)",
    "Master in Philosophy (MPh)",
    "Master in Quantitative Economics and Finance (MQE)",
    "Master in Strategy and International Management (SIM)",
    "Master in Supply Chain Management (MSCM)",
    "Master in Tax Law (MTaxLaw)",
    "Executive MBA (EMBA)",
]

# ---------------------------------------------------------------------------
# Eligible thesis supervisors per programme
# Each entry: { name, topics, procedure, topic_type }
#   topic_type: "own" | "given" | "both"
# ---------------------------------------------------------------------------

# Bachelor of Arts in Economics
SUPERVISORS_BA_ECON = [
    {
        "name": "Francesco Audrino",
        "full_title": "Prof. Dr. Francesco Audrino",
        "topics": ["Financial Econometrics", "Computational Statistics and Machine Learning", "Time Series Analysis", "Statistical Methods in Econometrics and Finance"],
        "topic_type": "both",
        "procedure": "Students should first get in contact via E-Mail in order to make an appointment for a personal meeting.",
    },
    {
        "name": "Johannes Binswanger",
        "full_title": "Prof. Dr. Johannes Binswanger",
        "topics": ["Machine Learning", "Macroeconomics", "Behavioral Economics", "Ideology and Campaigning"],
        "topic_type": "both",
        "procedure": "Student should first get in contact via E-Mail.",
    },
    {
        "name": "Stefan Bühler",
        "full_title": "Prof. Dr. Stefan Bühler",
        "topics": ["Microeconomics", "Game Theory", "Industrial Organization", "Regulation", "Antitrust Economics and Policy", "Network Economics", "Telecommunications"],
        "topic_type": "both",
        "procedure": "Students get in touch by filling in the application form (on website) and send it by E-Mail. A personal meeting will be arranged.",
    },
    {
        "name": "Bruno Caprettini",
        "full_title": "Prof. Ph.D. Bruno Caprettini",
        "topics": ["Trade and Development", "Political Economics", "Economic History"],
        "topic_type": "both",
        "procedure": "Student should first get in contact via E-Mail.",
    },
    {
        "name": "Guido Cozzi",
        "full_title": "Prof. Guido Cozzi, Ph.D.",
        "topics": ["Economic Growth", "Economics of Innovation", "Political Economy", "International Macroeconomics"],
        "topic_type": "both",
        "procedure": "Students should first get in contact via E-Mail in order to make an appointment for a personal meeting.",
    },
    {
        "name": "Enrico de Giorgi",
        "full_title": "Prof. Enrico de Giorgi, Ph.D.",
        "topics": ["Behavioural Finance", "Decision Analysis", "Risk Measurement and Management", "Data-driven Decision Making", "Ethical Artificial Intelligence"],
        "topic_type": "own",
        "procedure": "Students should first get in contact via E-Mail in order to make an appointment for a personal meeting.",
    },
    {
        "name": "Lyudmila Grigoryeva",
        "full_title": "Prof. Ph.D. Lyudmila Grigoryeva",
        "topics": ["Quantitative Economics"],
        "topic_type": "both",
        "procedure": "Student should first get in contact via E-Mail.",
    },
    {
        "name": "Mariana Lopes da Fonseca",
        "full_title": "Prof. Dr. Mariana Lopes da Fonseca",
        "topics": ["Public Economics", "Political Economy", "Institutional Influence"],
        "topic_type": "both",
        "procedure": "Student should first get in contact via E-Mail.",
    },
    {
        "name": "Sabrina Eisenbarth",
        "full_title": "Dr. Sabrina Eisenbarth",
        "topics": ["Environmental Economics", "Resource Economics"],
        "topic_type": "both",
        "procedure": "Student should first get in contact via E-Mail.",
    },
    {
        "name": "Patrick Emmenegger",
        "full_title": "Prof. Patrick Emmenegger",
        "topics": ["Comparative Welfare State", "Political Economy of Switzerland", "Regulation of Labor Markets", "Finance, Banks, and Tax Policy", "Political Role of Companies"],
        "topic_type": "own",
        "procedure": "Students should first get in contact via E-Mail in order to provide information about their academic background and their proposal.",
    },
    {
        "name": "Beatrix Eugster",
        "full_title": "Prof. Beatrix Eugster, Ph.D.",
        "topics": ["Labour Markets", "Health Economics", "Culture and Economics"],
        "topic_type": "own",
        "procedure": "Students should first get in contact via E-Mail in order to provide information about their academic background and their proposal.",
    },
    {
        "name": "Matthias Fengler",
        "full_title": "Prof. Dr. Matthias Fengler",
        "topics": ["Financial Econometrics and Statistics", "Empirical Finance"],
        "topic_type": "both",
        "procedure": "Students should first get in contact via E-Mail in order to make an appointment for a personal meeting.",
    },
    {
        "name": "Reto Föllmi",
        "full_title": "Prof. Dr. Reto Föllmi",
        "topics": ["Economic Growth", "Macroeconomics", "Distribution and Inequality", "International Trade"],
        "topic_type": "both",
        "procedure": "Student should first get in contact via E-Mail.",
    },
    {
        "name": "Alexander Geissler",
        "full_title": "Prof. Dr. Alexander Geissler",
        "topics": ["Health Economics", "Health Policy"],
        "topic_type": "own",
        "procedure": "Students should first get in contact via E-Mail (alexander.geissler@unisg.ch) in order to make an appointment for a personal meeting.",
    },
    {
        "name": "Alia Gizatullina",
        "full_title": "Prof. Alia Gizatullina, Ph.D.",
        "topics": ["Auction Theory", "Financial Markets", "Microeconomics", "Managerial Economics", "Game Theory"],
        "topic_type": "own",
        "procedure": "Students should first get in contact via E-Mail in order to make an appointment for a personal meeting.",
    },
    {
        "name": "Samuel Häfner",
        "full_title": "Prof. Ph.D. Samuel Häfner",
        "topics": ["Economic Growth", "Macroeconomics", "Distribution and Inequality", "International Trade"],
        "topic_type": "both",
        "procedure": "Student should first get in contact via E-Mail.",
    },
    {
        "name": "Roland Hodler",
        "full_title": "Prof. Dr. Roland Hodler",
        "topics": ["Development Economics", "Public Economics", "Political Economics"],
        "topic_type": "own",
        "procedure": "Students can find guidelines on www.rhodler.net",
    },
    {
        "name": "Winfried Koeniger",
        "full_title": "Prof. Dr. Winfried Koeniger",
        "topics": ["Labour Markets", "Consumption / Household Finance", "Macroeconomics"],
        "topic_type": "own",
        "procedure": "Student should first get in contact via E-Mail.",
    },
    {
        "name": "Martin Kolmar",
        "full_title": "Prof. Dr. Martin Kolmar",
        "topics": ["Applied Microeconomics", "Conflict and Competition Theory", "Theories of Justice", "Law & Economics", "Economic and Financial Policy", "Institutional Economics"],
        "topic_type": "own",
        "procedure": "Students should first get in contact via E-Mail in order to make an appointment for a personal meeting.",
    },
    {
        "name": "Markus Kondziella",
        "full_title": "Prof. Ph.D. Markus Kondziella",
        "topics": ["Macroeconometrics", "Firm Dynamics", "Economic Growth", "Wealth Inequality"],
        "topic_type": "own",
        "procedure": "Student should first get in contact via E-Mail.",
    },
    {
        "name": "Johanna Kutz",
        "full_title": "Prof. Dr. Johanna Kutz",
        "topics": ["Causal Machine Learning", "Microeconometrics"],
        "topic_type": "both",
        "procedure": "Student should first get in contact via E-Mail.",
    },
    {
        "name": "Michael Lechner",
        "full_title": "Prof. Dr. Michael Lechner",
        "topics": ["Econometrics", "Empirical Economic Research", "Labour Economics", "Sports Economics", "Machine Learning"],
        "topic_type": "own",
        "procedure": "Student should first get in contact via E-Mail.",
    },
    {
        "name": "Michèle Müller-Itten",
        "full_title": "Prof. Michèle Müller-Itten, Ph.D.",
        "topics": ["Rational Inattention", "Decision Theory", "Game Theory"],
        "topic_type": "both",
        "procedure": "Studierende sollen zunächst per E-Mail Kontakt aufnehmen.",
    },
    {
        "name": "Jana Mareckova",
        "full_title": "Prof. Dr. Jana Mareckova",
        "topics": ["Applied Econometrics - Labour Market", "Causal Machine Learning", "Shrinkage Methods", "Fairness", "Optimal Policy"],
        "topic_type": "both",
        "procedure": "Student should first get in contact via E-Mail.",
    },
    {
        "name": "Paolo Piacquadio",
        "full_title": "Prof. Paolo Piacquadio, Ph.D.",
        "topics": ["Applied Economics", "Public Economics", "Welfare Economics", "Optimal Redistribution Policies", "Inequality, Poverty, Mobility", "Intergenerational Equity", "Fairness", "Social Preferences"],
        "topic_type": "both",
        "procedure": "Student should first get in contact via E-Mail.",
    },
    {
        "name": "Ferdinand Rauch",
        "full_title": "Prof. Ph.D. Ferdinand Rauch",
        "topics": ["Urban Economics", "Trade", "Economic History"],
        "topic_type": "both",
        "procedure": "Student should first get in contact via E-Mail.",
    },
    {
        "name": "Dominik Sachs",
        "full_title": "Prof. Dr. Dominik Sachs",
        "topics": ["Macroeconomics", "Public Finance"],
        "topic_type": "both",
        "procedure": "Student should first get in contact via E-Mail.",
    },
    {
        "name": "Paul Söderlind",
        "full_title": "Prof. Paul Söderlind, Ph.D.",
        "topics": ["Finance (Asset Markets and Prices)", "Macroeconomics"],
        "topic_type": "own",
        "procedure": "Students should first get in contact via E-Mail in order to make an appointment for a personal meeting.",
    },
    {
        "name": "Tobias Sutter",
        "full_title": "Prof. Dr. Tobias Sutter",
        "topics": ["Data-driven Decision Making under Uncertainty", "Robust Machine Learning and Optimization", "Econometrics", "Optimal Policy Learning", "Operations Research"],
        "topic_type": "both",
        "procedure": "Student should first get in contact via E-Mail.",
    },
    {
        "name": "Martin Wolf",
        "full_title": "Prof. Dr. Martin Wolf",
        "topics": ["Monetary Economics", "International Economics", "Economic Growth"],
        "topic_type": "both",
        "procedure": "Student should first get in contact via E-Mail.",
    },
]

# Bachelor of Arts in International Affairs
SUPERVISORS_BA_BIA = [
    {
        "name": "Martin Albani",
        "full_title": "Dr. Martin Albani",
        "discipline": "Political Science",
        "topics": ["Peacebuilding", "Responding to Crisis"],
        "topic_type": "both",
    },
    {
        "name": "Eri Bertsou",
        "full_title": "Assistant Prof. Dr. Eri Bertsou",
        "discipline": "Political Science",
        "topics": ["Political Behaviour", "Populism and Technocracy", "Attitudes towards Experts", "Democracy and Democratic Backsliding", "Political Culture"],
        "topic_type": "both",
    },
    {
        "name": "Vanessa Boanada Fuchs",
        "full_title": "Assistant Prof. Dr. Vanessa Boanada Fuchs",
        "discipline": "Political Science",
        "topics": ["Natural Resources Governance", "Sustainable Development Goals", "Socio-environmental Entrepreneurship", "Human Rights and Development", "Indigenous People"],
        "topic_type": "both",
    },
    {
        "name": "Claudia Brühwiler",
        "full_title": "PD Dr. Claudia Brühwiler",
        "discipline": "Political Science",
        "topics": ["U.S. Politics", "American Conservatism", "American Political Thought", "Politics, Literature, Theater, and Art"],
        "topic_type": "both",
    },
    {
        "name": "Thomas Burri",
        "full_title": "Prof. Dr. Thomas Burri",
        "discipline": "Law",
        "topics": ["International Law", "European Law"],
        "topic_type": "both",
    },
    {
        "name": "Bruno Caprettini",
        "full_title": "Prof. Dr. Bruno Caprettini",
        "discipline": "Economics",
        "topics": ["Development", "Political Economy", "Economic History", "Technological Change and Growth", "Industrial Policy"],
        "topic_type": "both",
    },
    {
        "name": "James Davis",
        "full_title": "Prof. James Davis, Ph.D.",
        "discipline": "Political Science",
        "topics": ["Theories of International Relations", "International Security", "Foreign Policy Analysis", "Political Responsibility", "Political Psychology / Behavioral IR"],
        "topic_type": "both",
    },
    {
        "name": "Klaus Dingwerth",
        "full_title": "Prof. Dr. Klaus Dingwerth",
        "discipline": "Political Science",
        "topics": ["Global Governance / International Institutions", "Global Environmental Politics", "Political Theory", "International Ethics", "International Norms"],
        "topic_type": "both",
    },
    {
        "name": "Julian Eckl",
        "full_title": "Dr. Julian Eckl",
        "discipline": "Political Science",
        "topics": ["Foundational Norms and Institutions of International Society", "Global Health Governance", "Digitalization and Changing Knowledge Practices", "Political Ethnography and Qualitative Methods"],
        "topic_type": "both",
    },
    {
        "name": "Sabrina Eisenbarth",
        "full_title": "Prof. Dr. Sabrina Eisenbarth",
        "discipline": "Economics",
        "topics": ["Environmental Economics", "Economics of Climate Change", "Environmental Problems in a Globalized World"],
        "topic_type": "both",
    },
    {
        "name": "Patrick Emmenegger",
        "full_title": "Prof. Dr. Patrick Emmenegger",
        "discipline": "Political Science",
        "topics": ["Comparative Welfare State", "Political Economy of Switzerland", "Labor Market Policies", "The Politics of Taxation"],
        "topic_type": "both",
    },
    {
        "name": "Christoph Frei",
        "full_title": "Prof. Dr. Christoph Frei",
        "discipline": "Political Science",
        "topics": ["Theories of International Relations", "World Politics", "History of Political Ideas", "Evolution of Modern Statehood", "France, China, Middle East"],
        "topic_type": "both",
    },
    {
        "name": "Tina Freyburg",
        "full_title": "Prof. Tina Freyburg, Ph.D.",
        "discipline": "Political Science",
        "topics": ["Comparative Politics", "Democracy Research", "European Studies", "Information & Communication Technologies"],
        "topic_type": "both",
    },
    {
        "name": "Roy Gava",
        "full_title": "Assistant Prof. Dr. Roy Gava",
        "discipline": "Political Science",
        "topics": ["Comparative Public Policy", "Regulation and Governance", "Interest Groups and Advocacy", "Financial Regulation"],
        "topic_type": "both",
    },
    {
        "name": "Ali Gündüz",
        "full_title": "Prof. Dr. Ali Gündüz",
        "discipline": "Business",
        "topics": ["Digital Government", "Smart Ecosystems"],
        "topic_type": "both",
    },
    {
        "name": "Christoph Heusgen",
        "full_title": "Prof. Dr. Christoph Heusgen",
        "discipline": "Political Science",
        "topics": ["International Conflict", "United Nations", "World Order"],
        "topic_type": "both",
    },
    {
        "name": "Roland Hodler",
        "full_title": "Prof. Dr. Roland Hodler",
        "discipline": "Economics",
        "topics": ["Development Economics", "Political Economics", "Public Economics"],
        "topic_type": "both",
    },
    {
        "name": "Martin Kolmar",
        "full_title": "Prof. Dr. Martin Kolmar",
        "discipline": "Economics",
        "topics": ["Narratology", "Economics and Happiness", "The Sublime and the Foundations of Modern Society"],
        "topic_type": "both",
    },
    {
        "name": "Manali Kumar",
        "full_title": "Dr. Manali Kumar",
        "discipline": "Political Science",
        "topics": ["India", "Indo-Pacific Security & Politics", "Rising Powers and Power Transition", "Theories of International Relations", "Qualitative Methods"],
        "topic_type": "both",
    },
    {
        "name": "Stefan Legge",
        "full_title": "Dr. Stefan Legge",
        "discipline": "Economics",
        "topics": ["International Trade", "Business Economics"],
        "topic_type": "both",
    },
    {
        "name": "Dirk Lehmkuhl",
        "full_title": "Prof. Dirk Lehmkuhl, Ph.D.",
        "discipline": "Political Science",
        "topics": ["European Public Policies", "European Foreign Policy", "Comparative Regional Cooperation", "Multilevel Governance", "Social Innovation / Sustainability"],
        "topic_type": "both",
    },
    {
        "name": "Mariana Lopes da Fonseca",
        "full_title": "Assistant Prof. Dr. Mariana Lopes da Fonseca",
        "discipline": "Political Science",
        "topics": ["Public Economics", "Political Economy", "Institutional Influence"],
        "topic_type": "both",
    },
    {
        "name": "Reto Malacrida",
        "full_title": "Dr. Reto Malacrida",
        "discipline": "External Lecturer",
        "topics": ["WTO Law/Trade Policy", "International Competition Policy", "International Intergovernmental Dispute Settlement"],
        "topic_type": "both",
    },
    {
        "name": "Elsa Massoc",
        "full_title": "Assistant Prof. Dr. Elsa Massoc",
        "discipline": "Political Science",
        "topics": ["Political Economy of Finance and Banking", "Geo-economics and Weaponized Interdependence", "Green Industrial Policy", "Political Economy of Private and Public Investment"],
        "topic_type": "both",
    },
    {
        "name": "Simon Mayer",
        "full_title": "Prof. Dr. Simon Mayer",
        "discipline": "Computer Science",
        "topics": ["Ubiquitous Computing", "Technology Assessment", "Technology and Society"],
        "topic_type": "both",
    },
    {
        "name": "Paolo Piacquadio",
        "full_title": "Prof. Dr. Paolo Piacquadio",
        "discipline": "Economics",
        "topics": ["Public Economics", "Welfare Economics", "Optimal Redistribution Policies", "Inequality, Poverty, Mobility", "Intergenerational Equity", "Fairness", "Social Preferences"],
        "topic_type": "both",
    },
    {
        "name": "Simon Planzer",
        "full_title": "Dr. Simon Planzer",
        "discipline": "External Lecturer",
        "topics": ["Market and European Law", "Gaming & Entertainment", "Technology & Online Businesses", "Market and Risk Regulation"],
        "topic_type": "both",
    },
    {
        "name": "Sebastian Plappert",
        "full_title": "Dr. Sebastian Plappert",
        "discipline": "Political Science",
        "topics": ["International Conflict & Security", "Progress & International Order", "History of International Relations"],
        "topic_type": "both",
    },
    {
        "name": "David Preinerstorfer",
        "full_title": "Associate Prof. Dr. David Preinerstorfer",
        "discipline": "Economics",
        "topics": ["Causal Machine Learning and Big Data", "Optimal Decision-Making", "Empirical Data Analysis"],
        "topic_type": "both",
    },
    {
        "name": "Adrian Rinscheid",
        "full_title": "Assistant Prof. Dr. Adrian Rinscheid",
        "discipline": "Political Science",
        "topics": ["Climate and Environmental Policy", "Transport Policy", "Food and Agricultural Policy", "Political Discourse"],
        "topic_type": "both",
    },
    {
        "name": "Winfried Ruigrok",
        "full_title": "Prof. Winfried Ruigrok, Ph.D.",
        "discipline": "Business",
        "topics": ["International Executive Careers", "Role of the CEO and Top Management Teams in Multinational Corporations", "Boards of Directors", "Teams as an Organisational Model", "Globalisation vs. Deglobalisation at the Firm Level"],
        "topic_type": "both",
    },
    {
        "name": "Dominik Sachs",
        "full_title": "Prof. Dr. Dominik Sachs",
        "discipline": "Economics",
        "topics": ["Tax Transfer Systems", "Social Insurance and Redistribution", "Income Inequality and Social Mobility", "Family and Education Policy"],
        "topic_type": "both",
    },
    {
        "name": "Paul Schaudt",
        "full_title": "Dr. Paul Schaudt",
        "discipline": "Economics",
        "topics": ["Political Economy", "Economic Geography", "Development Economics"],
        "topic_type": "both",
    },
    {
        "name": "Kuno Schedler",
        "full_title": "Prof. Dr. Kuno Schedler",
        "discipline": "Business",
        "topics": ["Comparative Public Management", "Public Sector Accounting and Budgeting", "Organization Theory and Public Administration", "Public Corporate Governance", "Service Models in Public Administration"],
        "topic_type": "both",
    },
    {
        "name": "Ronny Seiger",
        "full_title": "Assistant Prof. Dr. Ronny Seiger",
        "discipline": "Computer Science",
        "topics": ["Industry 4.0", "Complex Event Processing", "Robotics", "Systems Engineering", "Mixed Reality"],
        "topic_type": "both",
    },
    {
        "name": "Hannah Smidt",
        "full_title": "Assistant Prof. Dr. Hannah Smidt",
        "discipline": "Political Science",
        "topics": ["International Organizations", "Civil Society and Repression", "International Peacekeeping and Peacebuilding"],
        "topic_type": "both",
    },
    {
        "name": "Manuela Spindler",
        "full_title": "Prof. Dr. Manuela Spindler",
        "discipline": "Political Science",
        "topics": ["Theories of International Relations", "Philosophy of Science", "Networked Thinking and Learning"],
        "topic_type": "both",
    },
    {
        "name": "Noémie Zurlinden",
        "full_title": "Dr. Noémie Zurlinden",
        "discipline": "Economics",
        "topics": ["Poverty Alleviation", "Development Economics"],
        "topic_type": "both",
    },
]

# Map programme short codes to their eligible supervisor lists
PROGRAMME_SUPERVISORS = {
    "Bachelor of Arts HSG in Economics (B.A. HSG)": SUPERVISORS_BA_ECON,
    "Bachelor of Arts HSG in International Affairs (B.A. HSG)": SUPERVISORS_BA_BIA,
    # Other programmes: no restriction (use full Alexandria list)
}

# ---------------------------------------------------------------------------
# Studyond-aligned fields taxonomy
# Maps our RESEARCH_AREAS to fields.json IDs for cross-platform compatibility
# ---------------------------------------------------------------------------

RESEARCH_AREA_TO_FIELD_IDS: dict[str, list[str]] = {
    "Accounting":                          ["field-24", "field-04"],
    "Arts Administration":                 ["field-04"],
    "Behavioral Science/Organizational Behaviour": ["field-16", "field-04"],
    "Business Communication":              ["field-15", "field-04"],
    "Business Education":                  ["field-19", "field-04"],
    "Business Law/Legal Environment":      ["field-14", "field-04"],
    "Computer Science":                    ["field-01"],
    "Conflict":                            ["field-25", "field-20"],
    "Consulting":                          ["field-04", "field-21"],
    "Data Analytics":                      ["field-02", "field-03"],
    "E-Business/E-commerce":               ["field-04", "field-01"],
    "Economics":                           ["field-13"],
    "Energy Management":                   ["field-17", "field-08"],
    "Entrepreneurship":                    ["field-23"],
    "Ethics":                              ["field-26"],
    "Finance/Banking":                     ["field-05"],
    "Health Services":                     ["field-12"],
    "History":                             ["field-25"],
    "Hotel/Restaurant/Tourism":            ["field-04"],
    "Human Resources Management":          ["field-28"],
    "Insurance":                           ["field-05"],
    "International Business":              ["field-22"],
    "International Politics":              ["field-25", "field-20"],
    "Leadership":                          ["field-04", "field-28"],
    "Management":                          ["field-04"],
    "Manufacturing and Technology":        ["field-09", "field-01"],
    "Marketing":                           ["field-06"],
    "Media":                               ["field-15"],
    "Mixed Methods":                       ["field-02"],
    "Operations Management":               ["field-27"],
    "Philosophy":                          ["field-26"],
    "Politics":                            ["field-25"],
    "Public Management":                   ["field-20"],
    "Qualitative Methods":                 ["field-02"],
    "Quantitative Methods":                ["field-02"],
    "Real Estate":                         ["field-05"],
    "Society":                             ["field-25"],
    "Sports Management":                   ["field-04"],
    "Statistics":                          ["field-02"],
    "Strategic Management":                ["field-21"],
    "Supply Chain":                        ["field-07"],
    "Sustainability":                      ["field-08"],
    "Taxation":                            ["field-24", "field-14"],
    "Transport/Logistics":                 ["field-07"],
}

# Recognised research areas on BusinessPlatform thesis marketplace
# Used for validation/normalisation during scraping and matching
RESEARCH_AREAS = [
    "Accounting",
    "Arts Administration",
    "Behavioral Science/Organizational Behaviour",
    "Business Communication",
    "Business Education",
    "Business Law/Legal Environment",
    "Computer Science",
    "Conflict",
    "Consulting",
    "Data Analytics",
    "E-Business/E-commerce",
    "Economics",
    "Energy Management",
    "Entrepreneurship",
    "Ethics",
    "Finance/Banking",
    "Health Services",
    "History",
    "Hotel/Restaurant/Tourism",
    "Human Resources Management",
    "Insurance",
    "International Business",
    "International Politics",
    "Leadership",
    "Management",
    "Manufacturing and Technology",
    "Marketing",
    "Media",
    "Mixed Methods",
    "Operations Management",
    "Philosophy",
    "Politics",
    "Public Management",
    "Qualitative Methods",
    "Quantitative Methods",
    "Real Estate",
    "Society",
    "Sports Management",
    "Statistics",
    "Strategic Management",
    "Supply Chain",
    "Sustainability",
    "Taxation",
    "Transport/Logistics",
]
